"""
report_formatter.py
Converts the coordinator's JSON output into a Markdown report.
"""

from datetime import datetime

ICONS = {"CRITICAL": "!!!", "HIGH": "!!", "MEDIUM": "!", "LOW": ".", "INFO": "i"}
AGENTS = [("security", "Security"), ("logic", "Logic"), ("readability", "Readability")]


def build_report(report: dict, filename: str) -> str:
    lines = []

    # ── Header ────────────────────────────────────────────────────
    lines += [
        "# Code Review Report",
        f"**File:** `{filename}`  |  **Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "| Score | Risk | Decision |",
        "|---|---|---|",
        f"| {report['overall_score']} / 10 | {report['risk_level']} | {report['recommendation']} |",
        "",
        "## Summary",
        report["executive_summary"],
        "",
        "## Issues by Severity",
    ]

    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        count = report["issues_by_severity"].get(sev, 0)
        if count:
            lines.append(f"- {ICONS[sev]} **{sev}**: {count}")

    # ── Top issues from coordinator ────────────────────────────────
    lines += ["", "##  Top Priority Issues"]
    for issue in report.get("top_issues", []):
        icon = ICONS.get(issue["severity"], "")
        lines += [
            f"### {icon} `{issue['id']}` {issue['title']} — Line {issue.get('line', '?')}",
            f"**Agent:** {issue['agent']}  |  **Severity:** {issue['severity']}",
            f"> **Fix:** {issue['fix']}",
            "",
        ]

    # ── Per-agent full findings ────────────────────────────────────
    for key, label in AGENTS:
        agent = report.get("agents", {}).get(key, {})
        issues = agent.get("issues", [])
        if not issues:
            continue

        lines += [
            f"## {label}",
            f"*{agent.get('summary', '')}*  —  Score: {agent.get('score', '?')}/10",
            "",
        ]

        for issue in issues:
            icon = ICONS.get(issue["severity"], "")
            lines += [
                f"### {icon} `{issue['id']}` {issue['title']} — Line {issue.get('line', '?')}",
                issue["description"],
                f"> **Fix:** {issue['fix']}",
                "",
            ]

        for positive in agent.get("positives", []):
            lines.append(f"-  {positive}")

    lines += ["", "---", "*Generated by Multi-Agent Code Review System — Powered by Google Gemini*"]
    return "\n".join(lines)